name: kweks-admin

services:
  api:
    build:
      context: ./server
    environment:
      PORT: 3001
      N8N_WEBHOOK_URL: https://n8n.kweks.co/webhook/04fca9af-9205-4dad-829b-a6a9d110d1a5
      N8N_WEBHOOK_TIMEOUT: ${N8N_WEBHOOK_TIMEOUT:-5000}
      SERVICES_CONFIG_PATH: /app/services.config.json
      DEVICES_CONFIG_PATH: /app/devices.config.json
      DOCKER_SOCKET_PATH: /var/run/docker.sock
    volumes:
      - ./server/services.config.json:/app/services.config.json:ro
      - ./server/devices.config.json:/app/devices.config.json:ro
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3033:3001"
    restart: unless-stopped

  web:
    build:
      context: ./client
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL:-/api}
    depends_on:
      - api
    ports:
      - "8087:80"
    restart: unless-stopped
